### ISSUE TITLE
Mickledore tag not compatable with mickledore

### ISSUE THREAD

**Issue by nevelshute** [betafive/meta-linux-mainline#22]
The mickledore tag is at HASH 18cbc87115fbc65c20ea0a5867c77895af78a2e4 but the mickledore   was erased from LAYERSERIES_COMPAT_meta-linux-mainline  at HASH  daa015b3bbdebacf0fca75995119370796056b79

Will you move the label or do we change the conf/layer.conf definition and add mickledore as below?

-LAYERSERIES_COMPAT_meta-linux-mainline = "dunfell kirkstone nanbield"
+LAYERSERIES_COMPAT_meta-linux-mainline = "dunfell kirkstone nanbield mickledore"

**Comment by pbrkr** [comment]
Ah, I should have stopped the mickledore branch updates before daa015b3bbdebacf0fca75995119370796056b79. I think the best fix will be to revert that commit on the mickledore branch.

**Comment by nevelshute** [comment]
GREAT
